#!/bin/bash

echo
echo in chrome browser
echo About:inspect
echo Then click Open dedicated DevTolls for Node
echo

cd "${0%/*}/.."
node --inspect-brk server/synergyServer/server.js -config server/config/localHTTP/_config.json
# pm2 start serverHTTPS.js -- -config /home/dwbolt/server/config/HTTPS/_config.json
