#!/bin/bash
echo
echo in chrome browser
echo About:inspect
echo Then click Open dedicated DevTolls for Node
echo

cd "${0%/*}"
cd ..
node --inspect-brk synergyServer/server.js -config config/localHTTPS/_config.json
