#!/bin/bash
echo
echo move to synergyRoot directory and init repostoris
cd "${0%/*}/.."
git submodule update --init --recursive

echo synergyServer - web server
cd server/synergyServer
pwd
git checkout main
echo 

echo move to each repositor and checkout main
echo lib - lib used in other websites
cd ../../synergy.sfcknox.org/_lib
pwd
git checkout main
echo 

echo synergy - web pages
cd ../synergy
pwd
git checkout main
echo 

echo synergyData - data to render pages
cd ../synergyData
pwd
git checkout main
echo 

echo
echo all done
echo
