#!/bin/bash

cd "${0%/*}"
cd ..
node server/synergyServer/server.js -config server/config/localHTTP/_config.json

# node      server/synergyServer/server.js    -config server/config/HTTPS/_config.json
# pm2 start server/synergyServer/server.js -- -config server/config/HTTPS/_config.json