#!/bin/bash

echo
echo in chrome browser
echo About:inspect
echo Then click Open dedicated DevTolls for Node
echo

cd "${0%/*}"
cd ..
node --inspect-brk server/synergyServer/server.js -config server/config/localHTTP/_config.json


